name = "pwascore"
compatibility_date = "2025-01-15"
main = ".output/server/index.mjs"

# Workers configuration
workers_dev = true
preview_urls = false

# Custom domain
routes = [
  { pattern = "pwascore.com", custom_domain = true }
]

# Compatibility flags
compatibility_flags = ["nodejs_compat"]

# Assets configuration
[assets]
directory = ".output/public"
